# Generated by Django 4.2.15 on 2024-08-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('House', 'House'), ('Hotel', 'Hotel'), ('Restaurant', 'Restaurant')], default='', max_length=123),
        ),
    ]
