# Generated by Django 4.2.15 on 2024-08-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_portal', '0002_house_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='house_name',
            new_name='name',
        ),
    ]
