# Generated by Django 4.2.15 on 2024-08-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_portal', '0004_alter_house_description_alter_house_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
