# Generated by Django 4.2.15 on 2024-08-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_portal', '0005_alter_house_bathrooms_alter_house_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('House', 'House'), ('Hostels', 'Hostels'), ('Hotel', 'Hotel'), ('Restaurant', 'Restaurant')], default='House', max_length=20),
        ),
    ]
