# Generated by Django 4.2.15 on 2024-08-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_portal', '0007_alter_house_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='house',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
