# Generated by Django 4.2.15 on 2024-08-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_portal', '0008_house_mail_house_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
