# Generated by Django 4.2.11 on 2024-05-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='House',
            new_name='house',
        ),
    ]
