# Generated by Django 4.2.11 on 2024-05-04 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0006_alter_house_owner'),
        ('customer_portal', '0002_rename_house_orders_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='car_dealer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='car_dealer_portal.cardealer'),
        ),
    ]
