# Generated by Django 4.2.11 on 2024-05-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0003_alter_orders_car_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='car_dealer',
        ),
    ]
