# Generated by Django 4.2.11 on 2024-05-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0002_alter_house_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(default='', upload_to='house_images/'),
        ),
    ]
