# Generated by Django 4.2.11 on 2024-05-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0003_house_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardealer',
            old_name='car_dealer',
            new_name='house_owner',
        ),
    ]
