# Generated by Django 4.2.11 on 2024-05-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0005_house_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_houses', to='car_dealer_portal.cardealer'),
        ),
    ]
